## Variable Construction

In [8]:
import sys
sys.path.append("..")

%load_ext autoreload
%autoreload 2

#### UKPS Data

**Participation:**

- Breadth of cultural participation — the number of distinct cultural activities that a respondent engaged in over the past 12 months.
- Volume of cultural participation — the frequency of engagement across these activities, transformed into minimum annual counts for comparability.

- Intensity=Volume_norm × Breadth_norm

**Well‑being:**

- mean index; check Cronbach’s α

**Controls:**

- gender, age, education, occupation, ethnicity

In [ ]:
import pandas as pd

ukps_df = pd.read_csv('../data/UKDA-9350-tab/tab/participation_2023-24_annual_data_safeguard.tab', sep="\t")
list(ukps_df.columns)

['ArchYcserial',
 'ArchIndivSerial',
 'ArchHHSerial',
 'Year',
 'Quarter',
 'wave',
 'mode',
 'SubSample',
 'ScreenReader',
 'QRCODE',
 'NUMADULTS',
 'SEX',
 'COHAB',
 'CHILDHH',
 'CARTS1_001',
 'CARTS1_002',
 'CARTS1_003',
 'CARTS1_004',
 'CARTS1_005',
 'CARTS1_006',
 'CARTS1_007',
 'CARTS1_008',
 'CARTS1_009',
 'CARTS1_010',
 'CARTS1_011',
 'CARTS1_012',
 'CARTS1_013',
 'CARTS1_998',
 'CARTS1_996',
 'CARTS1A_a',
 'CARTS1A_b',
 'CARTS1A_c',
 'CARTS1A_d',
 'CARTS1A_e',
 'CARTS1A_f',
 'CARTS1A_g',
 'CARTS1A_h',
 'CARTS1A_i',
 'CARTS1A_j',
 'CARTS1A_k',
 'CARTS1A_l',
 'CARTS1A_m',
 'CARTS1B_a_001',
 'CARTS1B_a_002',
 'CARTS1B_a_003',
 'CARTS1B_a_999',
 'CARTS1B_b_001',
 'CARTS1B_b_002',
 'CARTS1B_b_003',
 'CARTS1B_b_999',
 'CARTS1B_c_001',
 'CARTS1B_c_002',
 'CARTS1B_c_003',
 'CARTS1B_c_999',
 'CARTS1B_d_001',
 'CARTS1B_d_002',
 'CARTS1B_d_003',
 'CARTS1B_d_999',
 'CARTS1B_e_001',
 'CARTS1B_e_002',
 'CARTS1B_e_003',
 'CARTS1B_e_999',
 'CARTS1B_f_001',
 'CARTS1B_f_002',
 'CARTS1B_f_003',
 'CARTS1B_f_999',
 'CARTS1B_g_001',
 'CARTS1B_g_002',
 'CARTS1B_g_003',
 'CARTS1B_g_999',
 'CARTS1B_h_001',
 'CARTS1B_h_002',
 'CARTS1B_h_003',
 'CARTS1B_h_999',
 'CARTS1B_i_001',
 'CARTS1B_i_002',
 'CARTS1B_i_003',
 'CARTS1B_i_999',
 'CARTS1B_j_001',
 'CARTS1B_j_002',
 'CARTS1B_j_003',
 'CARTS1B_j_999',
 'CARTS1B_k_001',
 'CARTS1B_k_002',
 'CARTS1B_k_003',
 'CARTS1B_k_999',
 'CARTS1B_l_001',
 'CARTS1B_l_002',
 'CARTS1B_l_003',
 'CARTS1B_l_999',
 'CARTS1B_m_001',
 'CARTS1B_m_002',
 'CARTS1B_m_003',
 'CARTS1B_m_999',
 'FILMTYPE_001',
 'FILMTYPE_002',
 'FILMTYPE_003',
 'FILMTYPE_004',
 'FILMTYPE_005',
 'FILMTYPE_006',
 'FILMTYPE_007',
 'FILMTYPE_008',
 'FILMTYPE_009',
 'FILMTYPE_010',
 'FILMTYPE_998',
 'FILMTYPE_999',
 'ENVIRONA',
 'DENVIRONA',
 'ENVIRON1_001',
 'ENVIRON1_002',
 'ENVIRON1_003',
 'ENVIRON1_004',
 'ENVIRON1_005',
 'ENVIRON1_006',
 'ENVIRON1_007',
 'ENVIRON1_008',
 'ENVIRON1_009',
 'ENVIRON1_010',
 'ENVIRON1A',
 'ENVIRON2',
 'ENVIRON3',
 'ENVIRON6_001',
 'ENVIRON6_002',
 'ENVIRON6_003',
 'ENVIRON6_004',
 'ENVIRON6_005',
 'ENVIRON6_006',
 'ENVIRON6_007',
 'ENVIRON6_008',
 'ENVIRON6A',
 'CARTS2_001',
 'CARTS2_002',
 'CARTS2_003',
 'CARTS2_004',
 'CARTS2_005',
 'CARTS2_006',
 'CARTS2_007',
 'CARTS2_008',
 'CARTS2_009',
 'CARTS2_010',
 'CARTS2_011',
 'CARTS2_998',
 'CARTS2_996',
 'CARTS2A_a',
 'CARTS2A_b',
 'CARTS2A_c',
 'CARTS2A_d',
 'CARTS2A_e',
 'CARTS2A_f',
 'CARTS2A_g',
 'CARTS2A_h',
 'CARTS2A_i',
 'CARTS2A_j',
 'CARTS2A_k',
 'CARTS2B_a_001',
 'CARTS2B_a_002',
 'CARTS2B_a_003',
 'CARTS2B_a_999',
 'CARTS2B_b_001',
 'CARTS2B_b_002',
 'CARTS2B_b_003',
 'CARTS2B_b_999',
 'CARTS2B_c_001',
 'CARTS2B_c_002',
 'CARTS2B_c_003',
 'CARTS2B_c_999',
 'CARTS2B_d_001',
 'CARTS2B_d_002',
 'CARTS2B_d_003',
 'CARTS2B_d_999',
 'CARTS2B_e_001',
 'CARTS2B_e_002',
 'CARTS2B_e_003',
 'CARTS2B_e_999',
 'CARTS2B_f_001',
 'CARTS2B_f_002',
 'CARTS2B_f_003',
 'CARTS2B_f_999',
 'CARTS2B_g_001',
 'CARTS2B_g_002',
 'CARTS2B_g_003',
 'CARTS2B_g_999',
 'CARTS2B_h_001',
 'CARTS2B_h_002',
 'CARTS2B_h_003',
 'CARTS2B_h_999',
 'CARTS2B_i_001',
 'CARTS2B_i_002',
 'CARTS2B_i_003',
 'CARTS2B_i_999',
 'CARTS2B_j_001',
 'CARTS2B_j_002',
 'CARTS2B_j_003',
 'CARTS2B_j_999',
 'CARTS2B_k_001',
 'CARTS2B_k_002',
 'CARTS2B_k_003',
 'CARTS2B_k_999',
 'PAYPAPER',
 'CNARTP1_001',
 'CNARTP1_002',
 'CNARTP1_003',
 'CNARTP1_004',
 'CNARTP1_005',
 'CNARTP1_006',
 'CNARTP1_007',
 'CNARTP1_008',
 'CNARTP1_009',
 'CNARTP1_010',
 'CNARTP1_011',
 'CNARTP1_012',
 'CNARTP1_998',
 'CNARTP1_996',
 'WHYNOCULT_001',
 'WHYNOCULT_002',
 'WHYNOCULT_003',
 'WHYNOCULT_004',
 'WHYNOCULT_005',
 'WHYNOCULT_006',
 'WHYNOCULT_007',
 'WHYNOCULT_008',
 'WHYNOCULT_009',
 'WHYNOCULT_010',
 'WHYNOCULT_011',
 'WHYNOCULT_012',
 'WHYNOCULT_998',
 'CARTS3_001',
 'CARTS3_002',
 'CARTS3_003',
 'CARTS3_004',
 'CARTS3_005',
 'CARTS3_006',
 'CARTS3_007',
 'CARTS3_008',
 'CARTS3_009',
 'CARTS3_010',
 'CARTS3_011',
 'CARTS3_012',
 'CARTS3_998',
 'CARTS3_996',
 'CARTS3A_a',
 'CARTS3A_b',
 'CARTS3A_c',
 'CARTS3A_d',
 'CARTS3A_e',
 'CARTS3A_f',
 'CARTS3A_g',
 'CARTS3A_h',
 'CARTS3A_i',
 'CARTS3A_j',
 'CARTS3A_k',
 'CARTS3A_l',
 'CARTS3B_a_001',
 'CARTS3B_a_002',
 'CARTS3B_a_003',
 'CARTS3B_a_004',
 'CARTS3B_a_005',
 'CARTS3B_a_006',
 'CARTS3B_a_999',
 'CARTS3B_b_001',
 'CARTS3B_b_002',
 'CARTS3B_b_003',
 'CARTS3B_b_004',
 'CARTS3B_b_005',
 'CARTS3B_b_006',
 'CARTS3B_b_999',
 'CARTS3B_c_001',
 'CARTS3B_c_002',
 'CARTS3B_c_003',
 'CARTS3B_c_004',
 'CARTS3B_c_005',
 'CARTS3B_c_006',
 'CARTS3B_c_999',
 'CARTS3B_d_001',
 'CARTS3B_d_002',
 'CARTS3B_d_003',
 'CARTS3B_d_004',
 'CARTS3B_d_005',
 'CARTS3B_d_006',
 'CARTS3B_d_999',
 'CARTS3B_e_001',
 'CARTS3B_e_002',
 'CARTS3B_e_003',
 'CARTS3B_e_004',
 'CARTS3B_e_005',
 'CARTS3B_e_006',
 'CARTS3B_e_999',
 'CARTS3B_f_001',
 'CARTS3B_f_002',
 'CARTS3B_f_003',
 'CARTS3B_f_004',
 'CARTS3B_f_005',
 'CARTS3B_f_006',
 'CARTS3B_f_999',
 'CARTS3B_g_001',
 'CARTS3B_g_002',
 'CARTS3B_g_003',
 'CARTS3B_g_004',
 'CARTS3B_g_005',
 'CARTS3B_g_006',
 'CARTS3B_g_999',
 'CARTS3B_h_001',
 'CARTS3B_h_002',
 'CARTS3B_h_003',
 'CARTS3B_h_004',
 'CARTS3B_h_005',
 'CARTS3B_h_006',
 'CARTS3B_h_999',
 'CARTS3B_i_001',
 'CARTS3B_i_002',
 'CARTS3B_i_003',
 'CARTS3B_i_004',
 'CARTS3B_i_005',
 'CARTS3B_i_006',
 'CARTS3B_i_999',
 'CARTS3B_j_001',
 'CARTS3B_j_002',
 'CARTS3B_j_003',
 'CARTS3B_j_004',
 'CARTS3B_j_005',
 'CARTS3B_j_006',
 'CARTS3B_j_999',
 'CARTS3B_k_001',
 'CARTS3B_k_002',
 'CARTS3B_k_003',
 'CARTS3B_k_004',
 'CARTS3B_k_005',
 'CARTS3B_k_006',
 'CARTS3B_k_999',
 'CARTS3B_l_001',
 'CARTS3B_l_002',
 'CARTS3B_l_003',
 'CARTS3B_l_004',
 'CARTS3B_l_005',
 'CARTS3B_l_006',
 'CARTS3B_l_999',
 'CARTSVID_001',
 'CARTSVID_002',
 'CARTSVID_003',
 'CARTSVID_004',
 'CARTSVID_005',
 'CARTSVID_999',
 'CARTS4_001',
 'CARTS4_002',
 'CARTS4_003',
 'CARTS4_004',
 'CARTS4_998',
 'CARTS4_996',
 'CARTS4A_a',
 'CARTS4A_b',
 'CARTS4A_c',
 'CARTS4A_d',
 'CARTS4B_a_001',
 'CARTS4B_a_002',
 'CARTS4B_a_003',
 'CARTS4B_a_004',
 'CARTS4B_a_005',
 'CARTS4B_a_006',
 'CARTS4B_a_999',
 'CARTS4B_b_001',
 'CARTS4B_b_002',
 'CARTS4B_b_003',
 'CARTS4B_b_004',
 'CARTS4B_b_005',
 'CARTS4B_b_006',
 'CARTS4B_b_999',
 'CARTS4B_c_001',
 'CARTS4B_c_002',
 'CARTS4B_c_003',
 'CARTS4B_c_004',
 'CARTS4B_c_005',
 'CARTS4B_c_006',
 'CARTS4B_c_999',
 'CARTS4B_d_001',
 'CARTS4B_d_002',
 'CARTS4B_d_003',
 'CARTS4B_d_004',
 'CARTS4B_d_005',
 'CARTS4B_d_006',
 'CARTS4B_d_999',
 'CNARTP2_001',
 'CNARTP2_002',
 'CNARTP2_003',
 'CNARTP2_004',
 'CNARTP2_005',
 'CNARTP2_006',
 'CNARTP2_007',
 'CNARTP2_008',
 'CNARTP2_009',
 'CNARTP2_010',
 'CNARTP2_011',
 'CNARTP2_998',
 'CNARTP2_996',
 'SSTEAM_001',
 'SSTEAM_002',
 'SSTEAM_003',
 'SSTEAM_004',
 'SSTEAM_005',
 'SSTEAM_998',
 'SSTEAMFUT_001',
 'SSTEAMFUT_002',
 'SSTEAMFUT_003',
 'SSTEAMFUT_004',
 'SSTEAMFUT_005',
 'SSTEAMFUT_998',
 'SSTEAMFUT_999',
 'SOCPRESA',
 'SOCPRESO_001',
 'SOCPRESO_002',
 'SOCPRESO_003',
 'SOCPRESO_004',
 'SOCPRESO_005',
 'SOCPRESO_998',
 'SOCPRESO_996',
 'ARTPART12_001',
 'ARTPART12_002',
 'ARTPART12_003',
 'ARTPART12_004',
 'ARTPART12_005',
 'ARTPART12_006',
 'ARTPART12_007',
 'ARTPART12_998',
 'ARTPART12_996',
 'ARTPART12A_a',
 'ARTPART12A_b',
 'ARTPART12A_c',
 'ARTPART12A_d',
 'ARTPART12A_e',
 'ARTPART12A_f',
 'ARTPART12A_g',
 'ARTPART12B_a_001',
 'ARTPART12B_a_002',
 'ARTPART12B_a_003',
 'ARTPART12B_a_999',
 'ARTPART12B_b_001',
 'ARTPART12B_b_002',
 'ARTPART12B_b_003',
 'ARTPART12B_b_999',
 'ARTPART12B_c_001',
 'ARTPART12B_c_002',
 'ARTPART12B_c_003',
 'ARTPART12B_c_999',
 'ARTPART12B_d_001',
 'ARTPART12B_d_002',
 'ARTPART12B_d_003',
 'ARTPART12B_d_999',
 'ARTPART12B_e_001',
 'ARTPART12B_e_002',
 'ARTPART12B_e_003',
 'ARTPART12B_e_999',
 'ARTPART12B_f_001',
 'ARTPART12B_f_002',
 'ARTPART12B_f_003',
 'ARTPART12B_f_999',
 'ARTPART12B_g_001',
 'ARTPART12B_g_002',
 'ARTPART12B_g_003',
 'ARTPART12B_g_999',
 'ARTPARTWHY_001',
 'ARTPARTWHY_002',
 'ARTPARTWHY_003',
 'ARTPARTWHY_004',
 'ARTPARTWHY_005',
 'ARTPARTWHY_006',
 'ARTPARTWHY_007',
 'ARTPARTWHY_008',
 'ARTPARTWHY_009',
 'ARTPARTWHY_010',
 'ARTPARTWHY_011',
 'ARTPARTWHY_012',
 'ARTPARTWHY_013',
 'ARTPARTWHY_014',
 'ARTPARTWHY_998',
 'LOCPROV_001',
 'LOCPROV_002',
 'LOCPROV_003',
 'LOCPROV_004',
 'LOCPROV_005',
 'LOCPROV_998',
 'LOCPROV_996',
 'PAYCLASS',
 'ARTPARTIMP_001',
 'ARTPARTIMP_002',
 'ARTPARTIMP_003',
 'ARTPARTIMP_004',
 'ARTPARTIMP_005',
 'ARTPARTIMP_006',
 'ARTPARTIMP_007',
 'ARTPARTIMP_008',
 'ARTPARTIMP_009',
 'ARTPARTIMP_010',
 'ARTPARTIMP_011',
 'ARTPARTIMP_012',
 'ARTPARTIMP_013',
 'ARTPARTIMP_014',
 'ARTPARTIMP_015',
 'ARTPARTIMP_998',
 'ARTPARTIMP_996',
 'ARTPARTNON_001',
 'ARTPARTNON_002',
 'ARTPARTNON_003',
 'ARTPARTNON_004',
 'ARTPARTNON_005',
 'ARTPARTNON_006',
 'ARTPARTNON_007',
 'ARTPARTNON_008',
 'ARTPARTNON_009',
 'ARTPARTNON_010',
 'ARTPARTNON_011',
 'ARTPARTNON_012',
 'ARTPARTNON_013',
 'ARTPARTNON_014',
 'ARTPARTNON_998',
 'ARTPARTNON_996',
 'CLIBRARY1_001',
 'CLIBRARY1_002',
 'CLIBRARY1_003',
 'CLIBRARY1_004',
 'CLIBRARY1_998',
 'CLIBRARY1_996',
 'CFRELIB12',
 'CPARLI12A_001',
 'CPARLI12A_002',
 'CPARLI12A_003',
 'CPARLI12A_004',
 'CPARLI12A_005',
 'CPARLI12A_006',
 'CPARLI12A_998',
 'CPARLI12B_001',
 'CPARLI12B_002',
 'CPARLI12B_003',
 'CPARLI12B_004',
 'CPARLI12B_005',
 'CPARLI12B_006',
 'CPARLI12B_007',
 'CPARLI12B_008',
 'CPARLI12B_009',
 'CPARLI12B_010',
 'CPARLI12B_011',
 'CPARLI12B_012',
 'CPARLI12B_013',
 'CPARLI12B_998',
 'CPARLI12B_996',
 'SSLIBSAT',
 'CNLIWHYA_001',
 'CNLIWHYA_002',
 'CNLIWHYA_003',
 'CNLIWHYA_004',
 'CNLIWHYA_005',
 'CNLIWHYA_006',
 'CNLIWHYA_007',
 'CNLIWHYA_008',
 'CNLIWHYA_009',
 'CNLIWHYA_010',
 'CNLIWHYA_011',
 'CNLIWHYA_012',
 'CNLIWHYA_013',
 'CNLIWHYA_014',
 'CNLIWHYA_998',
 'CNLIWHYA_996',
 'CFRELIDIG',
 'CDIGLI12_001',
 'CDIGLI12_002',
 'CDIGLI12_003',
 'CDIGLI12_004',
 'CDIGLI12_005',
 'CDIGLI12_006',
 'CDIGLI12_007',
 'CDIGLI12_008',
 'CDIGLI12_009',
 'CDIGLI12_998',
 'CDIGLI12_996',
 'SSLIDIGSAT',
 'CLIBDIG_001',
 'CLIBDIG_002',
 'CLIBDIG_003',
 'CLIBDIG_004',
 'CLIBDIG_005',
 'CLIBDIG_998',
 'CLIBDIG_996',
 'CNLIWHYAD_001',
 'CNLIWHYAD_002',
 'CNLIWHYAD_003',
 'CNLIWHYAD_004',
 'CNLIWHYAD_005',
 'CNLIWHYAD_006',
 'CNLIWHYAD_007',
 'CNLIWHYAD_008',
 'CNLIWHYAD_009',
 'CNLIWHYAD_010',
 'CNLIWHYAD_011',
 'CNLIWHYAD_012',
 'CNLIWHYAD_998',
 'CNLIWHYAD_996',
 'CHERVIS12_001',
 'CHERVIS12_002',
 'CHERVIS12_003',
 'CHERVIS12_004',
 'CHERVIS12_005',
 'CHERVIS12_006',
 'CHERVIS12_007',
 'CHERVIS12_008',
 'CHERVIS12_009',
 'CHERVIS12_010',
 'CHERVIS12_998',
 'CFREHER12_a',
 'CFREHER12_b',
 'CFREHER12_c',
 'CFREHER12_d',
 'CFREHER12_e',
 'CFREHER12_f',
 'CFREHER12_g',
 'CFREHER12_h',
 'CFREHER12_i',
 'CFREHER12_j',
 'CVOLHER_a_001',
 'CVOLHER_a_002',
 'CVOLHER_a_003',
 'CVOLHER_a_999',
 'CVOLHER_b_001',
 'CVOLHER_b_002',
 'CVOLHER_b_003',
 'CVOLHER_b_999',
 'CVOLHER_c_001',
 'CVOLHER_c_002',
 'CVOLHER_c_003',
 'CVOLHER_c_999',
 'CVOLHER_d_001',
 'CVOLHER_d_002',
 'CVOLHER_d_003',
 'CVOLHER_d_999',
 'CVOLHER_e_001',
 'CVOLHER_e_002',
 'CVOLHER_e_003',
 'CVOLHER_e_999',
 'CVOLHER_f_001',
 'CVOLHER_f_002',
 'CVOLHER_f_003',
 'CVOLHER_f_999',
 'CVOLHER_g_001',
 'CVOLHER_g_002',
 'CVOLHER_g_003',
 'CVOLHER_g_999',
 'CVOLHER_h_001',
 'CVOLHER_h_002',
 'CVOLHER_h_003',
 'CVOLHER_h_999',
 'CVOLHER_i_001',
 'CVOLHER_i_002',
 'CVOLHER_i_003',
 'CVOLHER_i_999',
 'CVOLHER_j_001',
 'CVOLHER_j_002',
 'CVOLHER_j_003',
 'CVOLHER_j_999',
 'SSATTHER_001',
 'SSATTHER_002',
 'SSATTHER_003',
 'SSATTHER_004',
 'SSATTHER_005',
 'SSATTHER_006',
 'SSATTHER_007',
 'SSATTHER_008',
 'SSATTHER_009',
 'SSATTHER_010',
 'SSATTHER_011',
 'SSATTHER_998',
 'SSFEEHER_001',
 'SSFEEHER_002',
 'SSFEEHER_003',
 'SSFEEHER_999',
 'LIKHER',
 'SSTYPE_001',
 'SSTYPE_002',
 'SSTYPE_003',
 'SSTYPE_004',
 'SSTYPE_005',
 'SSTYPE_999',
 'IMPHER_001',
 'IMPHER_002',
 'IMPHER_003',
 'IMPHER_004',
 'IMPHER_005',
 'IMPHER_006',
 'IMPHER_007',
 'IMPHER_008',
 'IMPHER_009',
 'IMPHER_010',
 'IMPHER_011',
 'IMPHER_012',
 'IMPHER_013',
 'IMPHER_014',
 'IMPHER_998',
 'CCNHERWHYA_001',
 'CCNHERWHYA_002',
 'CCNHERWHYA_003',
 'CCNHERWHYA_004',
 'CCNHERWHYA_005',
 'CCNHERWHYA_006',
 'CCNHERWHYA_007',
 'CCNHERWHYA_008',
 'CCNHERWHYA_009',
 'CCNHERWHYA_010',
 'CCNHERWHYA_011',
 'CCNHERWHYA_012',
 'CCNHERWHYA_998',
 'CDIGHER12_001',
 'CDIGHER12_002',
 'CDIGHER12_003',
 'CDIGHER12_004',
 'CDIGHER12_998',
 'CFREHERDIG_a',
 'CFREHERDIG_b',
 'CFREHERDIG_c',
 'CFREHERDIG_d',
 'CREPAY5_a_001',
 'CREPAY5_a_002',
 'CREPAY5_a_003',
 'CREPAY5_a_004',
 'CREPAY5_a_005',
 'CREPAY5_a_006',
 'CREPAY5_a_999',
 'CREPAY5_b_001',
 'CREPAY5_b_002',
 'CREPAY5_b_003',
 'CREPAY5_b_004',
 'CREPAY5_b_005',
 'CREPAY5_b_006',
 'CREPAY5_b_999',
 'CREPAY5_c_001',
 'CREPAY5_c_002',
 'CREPAY5_c_003',
 'CREPAY5_c_004',
 'CREPAY5_c_005',
 'CREPAY5_c_006',
 'CREPAY5_c_999',
 'CREPAY5_d_001',
 'CREPAY5_d_002',
 'CREPAY5_d_003',
 'CREPAY5_d_004',
 'CREPAY5_d_005',
 'CREPAY5_d_006',
 'CREPAY5_d_999',
 'CCNHERWHYB_001',
 'CCNHERWHYB_002',
 'CCNHERWHYB_003',
 'CCNHERWHYB_004',
 'CCNHERWHYB_005',
 'CCNHERWHYB_006',
 'CCNHERWHYB_007',
 'CCNHERWHYB_008',
 'CCNHERWHYB_009',
 'CCNHERWHYB_010',
 'CCNHERWHYB_998',
 'PRIDE_D_a',
 'PRIDE_D_b',
 'PRIDE_D_c',
 'PRIDECULT_a',
 'PRIDECULT_b',
 'PRIDECULT_c',
 'PRIDEIMP1',
 'PRIDEIMP2',
 'PRIDEIMP3',
 'BELONG',
 'ARTCULATT_a',
 'ARTCULATT_b',
 'ARTCULATT_c',
 'ARTCULATT_d',
 'ARTCULATT_e',
 'ARTCULATT_f',
 'ARTCULATT_g',
 'CMUSVIS1_001',
 'CMUSVIS1_002',
 'CMUSVIS1_003',
 'CMUSVIS1_996',
 'CFREMUS12',
 'CVOLMUS_001',
 'CVOLMUS_002',
 'CVOLMUS_003',
 'CVOLMUS_999',
 'SSATTMUS_001',
 'SSATTMUS_002',
 'SSATTMUS_003',
 'SSATTMUS_004',
 'SSATTMUS_005',
 'SSATTMUS_006',
 'SSATTMUS_007',
 'SSATTMUS_008',
 'SSATTMUS_009',
 'SSATTMUS_010',
 'SSATTMUS_011',
 'SSATTMUS_012',
 'SSATTMUS_013',
 'SSATTMUS_998',
 'SSFEEMUS_001',
 'SSFEEMUS_002',
 'SSFEEMUS_003',
 'SSFEEMUS_999',
 'SSMUSTIM',
 'CNMUSWHYA_001',
 'CNMUSWHYA_002',
 'CNMUSWHYA_003',
 'CNMUSWHYA_004',
 'CNMUSWHYA_005',
 'CNMUSWHYA_006',
 'CNMUSWHYA_007',
 'CNMUSWHYA_008',
 'CNMUSWHYA_009',
 'CNMUSWHYA_010',
 'CNMUSWHYA_011',
 'CNMUSWHYA_012',
 'CNMUSWHYA_998',
 'CNMUSWHYA_996',
 'CMUSONL_001',
 'CMUSONL_002',
 'CMUSONL_003',
 'CMUSONL_998',
 'CFREMUSONL1_001',
 'CFREMUSONL1_002',
 'CFREMUSONL1_003',
 'CMUSONLWHY_001',
 'CMUSONLWHY_002',
 'CMUSONLWHY_003',
 'CMUSONLWHY_004',
 'CMUSONLWHY_005',
 'CMUSONLWHY_006',
 'CMUSONLWHY_007',
 'CMUSONLWHY_008',
 'CMUSONLWHY_009',
 'CMUSONLWHY_010',
 'CMUSONLWHY_998',
 'SMETDET_001',
 'SMETDET_002',
 'SMETDET_998',
 'SSPARMET_001',
 'SSPARMET_002',
 'SSPARMET_003',
 'SSPARMET_004',
 'SSPARMET_005',
 'CSPOLIVE',
 'CSPONUM',
 'CSPOSPEC_001',
 'CSPOSPEC_002',
 'CSPOSPEC_003',
 'CSPOSPEC_004',
 'CSPOSPEC_005',
 'CSPOSPEC_006',
 'CSPOSPEC_007',
 'CSPOSPEC_008',
 'CSPOSPEC_009',
 'CSPOSPEC_010',
 'CSPOSPEC_011',
 'CSPOSPEC_901',
 'CSPOSPEC_902',
 'CSPOSPEC_903',
 'CSPOSPEC_904',
 'CSPOSPEC_998',
 'CSPOPROF',
 'CSPOPROFB',
 'NOSPORT_001',
 'NOSPORT_002',
 'NOSPORT_003',
 'NOSPORT_004',
 'NOSPORT_005',
 'NOSPORT_006',
 'NOSPORT_007',
 'NOSPORT_008',
 'NOSPORT_009',
 'NOSPORT_010',
 'NOSPORT_011',
 'NOSPORT_998',
 'SSSPOWHI_001',
 'SSSPOWHI_002',
 'SSSPOWHI_003',
 'SSSPOWHI_004',
 'SSSPOWHI_005',
 'SSSPOWHI_006',
 'SSSPOWHI_007',
 'SSSPOWHI_008',
 'SSSPOWHI_009',
 'SSSPOWHI_010',
 'SSSPOWHI_011',
 'SSSPOWHI_901',
 'SSSPOWHI_902',
 'SSSPOWHI_903',
 'SSSPOWHI_904',
 'SSSPOWHI_905',
 'SSSPOWHI_998',
 'SSGAMATT',
 'SSBETATT2',
 'SSGAMLIV',
 'SSBETLIV',
 'CDOMT12',
 'CDOMWHE1',
 'CDOMLON',
 'CDOMATT',
 'CDOMCUL_001',
 'CDOMCUL_002',
 'CDOMCUL_003',
 'CDOMCUL_004',
 'CDOMCUL_005',
 'CDOMCUL_998',
 'CDOMNOHOL_001',
 'CDOMNOHOL_002',
 'CDOMNOHOL_003',
 'CDOMNOHOL_004',
 'CDOMNOHOL_005',
 'CDOMNOHOL_006',
 'CDOMNOHOL_007',
 'CDOMNOHOL_008',
 'CDOMNOHOL_009',
 'CDOMNOHOL_010',
 'CDOMNOHOL_011',
 'CDOMNOHOL_998',
 'CEVEAW_001',
 'CEVEAW_002',
 'CEVEAW_003',
 'CEVEAW_004',
 'CEVEAW_005',
 'CEVEAW_998',
 'CMAJE12_001',
 'CMAJE12_002',
 'CMAJE12_003',
 'CMAJE12_004',
 'CMAJE12_998',
 'SSPART22_a_001',
 'SSPART22_a_002',
 'SSPART22_a_003',
 'SSPART22_a_004',
 'SSPART22_a_005',
 'SSPART22_a_006',
 'SSPART22_a_007',
 'SSPART22_a_008',
 'SSPART22_a_999',
 'SSPART22_b_001',
 'SSPART22_b_002',
 'SSPART22_b_003',
 'SSPART22_b_004',
 'SSPART22_b_005',
 'SSPART22_b_006',
 'SSPART22_b_007',
 'SSPART22_b_008',
 'SSPART22_b_999',
 'SSPART22_c_001',
 'SSPART22_c_002',
 'SSPART22_c_003',
 'SSPART22_c_004',
 'SSPART22_c_005',
 'SSPART22_c_006',
 'SSPART22_c_007',
 'SSPART22_c_008',
 'SSPART22_c_999',
 'SSPART22_d_001',
 'SSPART22_d_002',
 'SSPART22_d_003',
 'SSPART22_d_004',
 'SSPART22_d_005',
 'SSPART22_d_006',
 'SSPART22_d_007',
 'SSPART22_d_008',
 'SSPART22_d_999',
 'CMAJE12FUT',
 'CEVEENGHOWQPJ_001',
 'CEVEENGHOWQPJ_002',
 'CEVEENGHOWQPJ_003',
 'CEVEENGHOWQPJ_004',
 'CEVEENGHOWQPJ_005',
 'CEVEENGHOWQPJ_006',
 'CEVEENGHOWQPJ_007',
 'CEVEENGHOWQPJ_008',
 'CEVEENGHOWQPJ_999',
 'CINTUSE',
 'CINTOFT',
 'CSMARTU_001',
 'CSMARTU_002',
 'CSMARTU_003',
 'CSMARTU_004',
 'CSMARTU_005',
 'CSMARTU_006',
 'CSMARTU_007',
 'CSMARTU_998',
 'SSSMARTH_001',
 'SSSMARTH_002',
 'SSSMARTH_003',
 'SSSMARTH_004',
 'SSSMARTH_005',
 'SSSMARTH_006',
 'SSSMARTH_007',
 'SSSMARTH_998',
 'CSMARTD_a',
 'CSMARTD_b',
 'CSMARTD_c',
 'CSMARTD_d',
 'CSMARTD_e',
 'CSMARTD_f',
 'CSMARTD_g',
 'CSMARTD_h',
 'CSMARTD_OTH',
 'CSMARTD_OTH_001',
 'CSMARTD_OTH_002',
 ...]

In [ ]:
ukps_df.ArchYcserial.nunique() == len(ukps_df)

True

### Participation

In [3]:
import re

binary_phys_part = set([x for x in ukps_df.columns if re.search("^CARTS[12]_0", x)])
freq_phys_part = set([x for x in ukps_df.columns if re.search("^CARTS[12]A_[a-z]", x)])

binary_digi_part = set([x for x in ukps_df.columns if re.search("^CARTS[34]_0", x)])
freq_digi_part = set([x for x in ukps_df.columns if re.search("^CARTS[34]A_[a-z]", x)])

recode_freq = {
    -5: pd.NA,
    -4: pd.NA,
    -3: pd.NA,
    1: 52,
    2: 12,
    3: 3,
    4: 2,
    5: 1,
    999: pd.NA,
}

ukps_df_participation = ukps_df.assign(
    phys_breath = ukps_df.loc[:, list(binary_phys_part)].gt(0).sum(axis=1),
    digi_breath = ukps_df.loc[:, list(binary_digi_part)].gt(0).sum(axis=1),
    phys_depth = ukps_df.loc[:, list(freq_phys_part)].replace(recode_freq).sum(axis=1),
    digi_depth = ukps_df.loc[:, list(freq_digi_part)].replace(recode_freq).sum(axis=1),
)[['ArchYcserial', 'phys_breath', 'digi_breath', 'phys_depth', 'digi_depth']]

ukps_df_participation.head()

   ArchYcserial  phys_breath  digi_breath phys_depth digi_depth
0      31000061            4            7          7        186
1      31000071            2            1         13          3
2      31000081           11           12         92        216
3      31000281            5            9          9        197
4      31000282            9            9         30        139

### Well-being

In [4]:
wellbeing_pos = set([x for x in ukps_df.columns if re.search("^WELLB[123]$", x)])

recode_wellb = {
    -5: pd.NA,
    -4: pd.NA,
    -3: pd.NA,
    997: pd.NA,
}

ukps_df_wellbeing = ukps_df.assign(
    WELLB4_rev = 10-ukps_df['WELLB4'].replace(recode_wellb),
    wellbeing = lambda x: x.loc[:, list(wellbeing_pos)+['WELLB4_rev']].replace(recode_wellb).mean(axis=1),
)[['ArchYcserial', 'wellbeing']]

ukps_df_wellbeing.head()

   ArchYcserial wellbeing
0      31000061       6.5
1      31000071       7.5
2      31000081      7.25
3      31000281      3.25
4      31000282       7.0

In [ ]:
### TBC check alpha

### Control

In [5]:
control_vars = ['SEX', 'AGEBAND', 'NSSEC_5', 'EDUCAT4', 'ETHNIC_NET_Safeguard'] #gender age, education, occupation, ethnicity (only white non-white?)

recode_ctrl = {
    -5: pd.NA,
    -4: pd.NA,
    -3: pd.NA,
    997: pd.NA,
    999: pd.NA,
}

ukps_df_controls = ukps_df[['ArchYcserial']+control_vars].replace(recode_ctrl)

ukps_df_controls.head()

   ArchYcserial SEX AGEBAND NSSEC_5 EDUCAT4 ETHNIC_NET_Safeguard
0      31000061   1       4       1       1                    1
1      31000071   2       5       1       7                    1
2      31000081   2       3    <NA>       1                    1
3      31000281   2       3       1       7                    1
4      31000282   1       2       1       4                    1

### Final DF

In [9]:
from data.ukps_data_dict import lad23cd_codes

ukps_vars_df = ukps_df_participation.merge(
    ukps_df_wellbeing, how='left', on='ArchYcserial'
).merge(
    ukps_df_controls, how='left', on='ArchYcserial'
).merge(
    ukps_df.assign(LAD23CD = ukps_df.lad23cd.map(lad23cd_codes))[['ArchYcserial', 'LAD23CD']], how='left', on='ArchYcserial'
)

ukps_vars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171748 entries, 0 to 171747
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ArchYcserial          171748 non-null  int64
 1   phys_breath           171748 non-null  int64
 2   digi_breath           171748 non-null  int64
 3   phys_depth            171748 non-null  object
 4   digi_depth            171748 non-null  object
 5   wellbeing             168254 non-null  object
 6   SEX                   168801 non-null  object
 7   AGEBAND               168928 non-null  object
 8   NSSEC_5               147855 non-null  object
 9   EDUCAT4               121965 non-null  object
 10  ETHNIC_NET_Safeguard  165475 non-null  object
 11  LAD23CD               171748 non-null  object
dtypes: int64(3), object(9)
memory usage: 15.7+ MB